import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/header";
import Footer from "../components/footer";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Hono | nextjs",
  description: "Generated by hono",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-CN">
      <head>
        <title>ghproxy plus</title>
      </head>
      <Toaster position="top-center" />
      <body className="font-sans antialiased">
        <div className="min-h-screen flex flex-col bg-background">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
